version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    ports:
      - 15672:15672

  reporter-init:
    image: reporter-init
    env_file:
      - config.env
    volumes:
      - ./reports:/twitter_reporter/reports
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  reporter-filter-parser:
    image: reporter-filter-parser
    env_file:
      - config.env
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  reporter-analyzer:
    image: reporter-analyzer
    env_file:
      - config.env
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  reporter-user-reducer:
    image: reporter-user-reducer
    env_file:
      - config.env
    volumes:
      - ./reports:/twitter_reporter/reports
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  reporter-date-reducer:
    image: reporter-date-reducer
    env_file:
      - config.env
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  reporter-date-agreggator:
    image: reporter-date-aggregator
    env_file:
      - config.env
    volumes:
      - ./reports:/twitter_reporter/reports
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
