version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    ports:
        - 15672:15672

  twitter-reporter:
    image: twitter-reporter
    env_file:
      - config.env
    volumes:
      - ./reports:/twitter_reporter/reports
    links:
      - rabbitmq
    depends_on:
        - rabbitmq
    restart: on-failure
