rabbitmq:
  image: rabbitmq:3.7.14-management
  ports:
      - 15672:15672

twitter-reporter:
  image: twitter_reporter
  env_file:
    - config.env
  volumes:
    - ./reports :/src/reports
  links:
    - rabbitmq
  depends_on:
      - rabbitmq
